imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%_%kernel.environment%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

mink:
    base_url:   http://evercodelab.dev/app_test.php