AppDefaultBundle:
    resource: "@AppDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

AppUserBundle:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /greenbird

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /greenbird

php_master_class:
    pattern: /php-master-class
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AppDefaultBundle:Default:phpMasterClass.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false