AppDefaultBundle:
    resource: "@AppDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

AppUserBundle:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /greenbird

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /greenbird

#Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /_internal
