services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]


## Admin resources
    app.user.admin.user:
        class: App\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Пользователи}
        arguments: [null, App\UserBundle\Entity\User, SonataAdminBundle:CRUD]

    app.client.admin.client:
        class: App\DefaultBundle\Admin\ClientsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Клиенты, label: Клиенты}
        arguments: [null, App\DefaultBundle\Entity\Client, SonataAdminBundle:CRUD]
    app.client.admin.portfolio:
        class: App\DefaultBundle\Admin\PortfolioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Клиенты, label: Портфолио}
        arguments: [null, App\DefaultBundle\Entity\Portfolio, SonataAdminBundle:CRUD, @security.context]