<?php

namespace App\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findAlias($Alias)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM PagesBundle:Page p
                WHERE p.Alias = :Alias
            ')->setParameter('Alias', $Alias);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}