parameters:
#    app_clients.example.class: App\ClientsBundle\Example

services:
#    app_clients.example:
#        class: %app_clients.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
