// Generated by CoffeeScript 1.6.2
(function() {
    var collapseAboutBlock, deselectTemiList, extendAboutBlock, hideMasterclass, showMasterclass, showMission, showTeam;

    extendAboutBlock = function() {
        return $("#aboutus").addClass('extended');
    };

    collapseAboutBlock = function() {
        return $("#aboutus").removeClass('extended');
    };

    deselectTemiList = function() {
        var item, items, _i, _len, _results;

        items = $('.b-temi-list').children('.item').toArray();
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
            item = items[_i];
            _results.push($(item).removeClass('active'));
        }
        return _results;
    };

    showTeam = function() {
        $('#mission-block').addClass('hidden');
        $('#team-block').removeClass('hidden');
        $('#about-team-switch').addClass('active');
        return extendAboutBlock();
    };

    showMission = function() {
        $('#team-block').addClass('hidden');
        $('#mission-block').removeClass('hidden');
        $('#about-mission-switch').addClass('active');
        return extendAboutBlock();
    };

    $(document).on('click', '#about-team-switch', function() {
        if ($(this).hasClass('active')) {
            deselectTemiList();
            return collapseAboutBlock();
        } else {
            if ($('#about-mission-switch').hasClass('active')) {
                collapseAboutBlock();
                deselectTemiList();
                $('#about-team-switch').addClass('active');
                return setTimeout((function() {
                    return showTeam();
                }), 650);
            } else {
                return showTeam();
            }
        }
    });

    $(document).on('click', '#about-mission-switch', function() {
        if ($(this).hasClass('active')) {
            deselectTemiList();
            return collapseAboutBlock();
        } else {
            if ($('#about-team-switch').hasClass('active')) {
                collapseAboutBlock();
                deselectTemiList();
                $('#about-mission-switch').addClass('active');
                return setTimeout((function() {
                    return showMission();
                }), 650);
            } else {
                return showMission();
            }
        }
    });

}).call(this);
